version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 6060:27017
  keycloak:
    image: antonioelefante10/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8080:8080
  node:
    restart: always
    build: .
    ports:
      - 3050:3050
    links:
      - "mongodb:mongodb"
      - "keycloak:localhost"
    depends_on:
      - mongodb
      - keycloak